#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "2af3352bc8094bbf8e89dca112c138c1"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "563b547f-8683-40d9-ada5-79891ce51a5c"
preview_database_id = "563b547f-8683-40d9-ada5-79891ce51a5c"
migrations_dir = "app/drizzle"
